"use client";

import Head from "next/head";

import { getCurrentVoting } from "../../services/Web3Service";
import { useEffect, useState } from "react";

export default function Vote() {
  const [currentVoting, setCurrentVoting] = useState<any>();

  async function handleCurrentVoting() {
    const result = await getCurrentVoting();
    setCurrentVoting(result);

    console.log({ result });
  }

  useEffect(() => {
    handleCurrentVoting();
  }, []);

  return (
    <>
      <Head>
        <title>Voting System</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-between p-24"></main>
    </>
  );
}
