"use client";

import Head from "next/head";

import { login } from "../services/Web3Service";

import { useRouter } from "next/navigation";

export default function Home() {
  const router = useRouter();

  async function handleConnectToMetaMask() {
    try {
      await login();

      router.push("/vote");
    } catch (err: any) {
      throw new Error(err);
    }
  }

  return (
    <>
      <Head>
        <title>Voting System</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-between p-24">
        <button onClick={handleConnectToMetaMask}>Connect to MetaMask</button>
      </main>
    </>
  );
}
